# Generated by Django 5.0.3 on 2024-04-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='national_id_number',
            new_name='id_number',
        ),
    ]
