# Generated by Django 5.0.3 on 2024-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_national_id_number_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='emergency_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
