# Generated by Django 5.0.3 on 2024-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_emergencycontact_emergency_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='national_id_number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='boda_username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='destination',
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
