# Generated by Django 5.0.3 on 2024-04-05 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_stageadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='stage',
        ),
    ]
