# Generated by Django 5.0.3 on 2024-04-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_is_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageadmin',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
