# Generated by Django 5.0.3 on 2024-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='destination',
        ),
        migrations.AlterField(
            model_name='customer',
            name='boda_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
