# Generated by Django 5.0.3 on 2024-04-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_customer_destination_alter_customer_boda_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='boda_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
