# Generated by Django 5.0.3 on 2024-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_emergency_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
