# Generated by Django 5.0.3 on 2024-04-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_emergency_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
